### ISSUE TITLE
Label doesn't seem to be aligned correctly when changing the text

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#38]
If a label is centered and I changed the text, it no longer seems to be center aligned.

Found this when working on PIS changing the TransferButton from "Transfer" to "Cancel". Don't think its a Button bug.

Think this means @tgrenbergj

**Comment by tgrenbergj** [comment]
How can I test this in your scene?  I can't seem to reproduce this.

**Comment by Tanner** [comment]
Try now with 147284f. You can see the text isn't aligned when Cancel is on.

Go to PIS. Add an item to the bin. Note TransferButton. Hit "Transfer". Note the "Cancel".

**Comment by tgrenbergj** [comment]
You need to pass in a label that is the same width as the button, and also set it to center alignment before you pass it in.  

If you just pass in a string to a label, it makes its final width as the width of the text, and really is never meant to be updated.

so instead of:

transferButton = new Button(container, BUTTON_WIDTH, BUTTON_HEIGHT, new Label(container, fieldFont, Color.white, ConstantStore.get("PARTY_INVENTORY_SCENE", "TRANSFER")));

you need something like

Label tempLabel = new Label(container, BUTTON_WIDTH, fieldFont, Color.white, ConstantStore.get("PARTY_INVENTORY_SCENE", "TRANSFER"));
tempLabel.setAlignment(Alignment.Center);
transferButton = new Button(container, BUTTON_WIDTH, BUTTON_HEIGHT, tempLabel);
